

export enum ENUM_PERMISSIONS {
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_READ = 'USER_READ',
    USER_DELETE = 'USER_DELETE',
    PROFILE_UPDATE = 'PROFILE_UPDATE',
    PROFILE_READ = 'PROFILE_READ',
    
    
    JOB_UPDATE = 'JOB_UPDATE',
    JOB_READ = 'JOB_READ',
    JOB_CREATE = 'JOB_CREATE',
    JOB_DELETE = 'JOB_DELETE',
    
    ROLE_READ='ROLE_READ',

    APPLICATION_CREATE = 'APPLICATION_CREATE',
    APPLICATION_UPDATE = 'APPLICATION_UPDATE',
    APPLICATION_READ = 'APPLICATION_READ',
    APPLICATION_DELETE = 'APPLICATION_DELETE',
}

export const PERMISSION_META_KEY = 'PERMISSION_META_KEY';
